### ISSUE TITLE
NexusProvider.groovy file does not exist in master branch

### ISSUE THREAD

**Issue by tsadoklevi** [sonatype-nexus-community/circleci-nexus-orb#13]
NexusProvider.groovy file does not exist in master branch

**Comment by bhamail** [comment]
I ran into the same problem: The required groovy script is not downloaded by the install step.

You get an error like this:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/circleci/project/NexusPublisher.groovy: 1: expecting EOF, found ':' @ line 1, column 4.
   404: Not Found
      ^

1 error
```

The problem is due to the resulting NexusPublisher.groovy containing nothing but the result of the failed curl command when trying to "install":

```
404: Not Found
```

Trying to find where the file actually lives.

Also, sorry for the similar file naming madness: 
`NexusPublisher.groovy` is a file that is downloaded during install (when successful).
`NexusProvider.groovy` is not a file I recognize, and I don't see it needed/used anywhere.

**Comment by collinpeters** [comment]
> NexusProvider.groovy file does not exist in master branch

Just to clarify, `NexusProvider.groovy` is in the sonatype-nexus-community/docker-nexus-platform-cli repo here: https://github.com/sonatype-nexus-community/docker-nexus-platform-cli/blob/master/src/main/groovy/NexusPublisher.groovy

**Comment by bhamail** [comment]
The currently published version of this Orb (v1.0.2) has the wrong URL for downloading the `NexusPublisher.groovy` file. The correct url is in the current master branch here: https://github.com/sonatype-nexus-community/circleci-nexus-orb/blob/master/orb.yml#L33

Perhaps all that is needed to fix this is a new release to the CircleCI Orb repository of the current master branch?

**Comment by sunggun-yu** [comment]
Any plan for publishing latest master branch?

**Comment by collinpeters** [comment]
1.0.3 was just released. Please let us know if you have further issues.
https://circleci.com/orbs/registry/orb/sonatype/nexus-platform-orb
